[project]
name = "student-attendance-system"
version = "0.1.0"
description = "A Streamlit-based student attendance tracking system with biometric authentication"
requires-python = ">=3.11"
authors = [{name = "Your Name", email = "your.email@example.com"}]
keywords = ["streamlit", "attendance", "biometric", "tracking", "student"]

[project.dependencies]
numpy = { version = ">=2.2.3" }
pandas = { version = ">=2.2.3" }
plotly = { version = ">=6.0.0" }
streamlit = { version = ">=1.42.1" }
