[project]
name = "student-attendance-system"
version = "0.1.0"
description = "A Streamlit-based student attendance tracking system with biometric authentication"
requires-python = ">=3.10"
[project.dependencies]
numpy = ">=2.2.3"
pandas = ">=2.2.3"
plotly = ">=6.0.0"
streamlit = ">=1.42.1"
